---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsign
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-ca-2024
  namespace: cert-manager
spec:
  issuerRef:
    name: selfsign
    kind: ClusterIssuer
    group: cert-manager.io
  isCA: true
  commonName: internal-ca-2024
  secretName: internal-ca-2024-secret
  duration: 87600h  # 24h * 365d * 10y
  renewBefore: 336h # 24h * 14d
  privateKey:
    algorithm: ECDSA
    size: 256
