---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: internal-ca-bundle
  namespace: cert-manager
spec:
  sources:
    - useDefaultCAs: true
    - secret:
        name: "internal-ca-2024-secret"
        key: "tls.crt"
  target:
    configMap:
      key: "trust-bundle.pem"
