---
apiVersion: v1
kind: Namespace
metadata:
  name: plaintext
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plaintext-server
  namespace: plaintext
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: plaintext-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plaintext-server
    spec:
      containers:
        - name: server
          image: tls-example-server:latest
          imagePullPolicy: Never
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8000
          livenessProbe:
            grpc:
              port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: plaintext
spec:
  ports:
    - name: grpc
      protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app.kubernetes.io/name: plaintext-server
