---
apiVersion: v1
kind: Namespace
metadata:
  name: secure
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server
  namespace: secure
spec:
  secretName: server-tls
  commonName: api
  dnsNames:
    - api
    - api.secure.svc
    - api.secure.svc.cluster.local
  issuerRef:
    name: internal
    kind: ClusterIssuer
    group: cert-manager.io
